# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license.
#
# If you run into issue wrt. referenced resources when settings this build up, cf. here:
#   https://github.com/Microsoft/vsts-agent/issues/1301 wrt. ConnectedServiceName
#
# TODO describe parameters
resources:
- repo: self
  clean: true

variables:
  SIGN_PARAMS_JAVA: |
    [
      {
        "keyCode": "CP-447347-Java",
        "operationSetCode": "JavaSign",
        "parameters": [
        {
          "parameterName": "SigAlg",
          "parameterValue": "SHA256withRSA"
        },
        {
          "parameterName": "Timestamp",
          "parameterValue": "-tsa http://sha256timestamp.ws.digicert.com/sha256/timestamp"
        }
        ],
        "toolName": "sign",
        "toolVersion": "1.0"
      },
      {
        "keyCode": "CP-447347-Java",
        "operationSetCode": "JavaVerify",
        "parameters": [ ],
        "toolName": "sign",
        "toolVersion": "1.0"
      }
    ]
  SIGN_PARAMS_DLL: |
    [
      {
        "keyCode": "CP-230012",
        "operationSetCode": "SigntoolSign",
        "parameters": [
          {
            "parameterName": "OpusName",
            "parameterValue": "Microsoft"
          },
          {
            "parameterName": "OpusInfo",
            "parameterValue": "http://www.microsoft.com"
          },
          {
            "parameterName": "PageHash",
            "parameterValue": "/NPH"
          },
          {
            "parameterName": "FileDigest",
            "parameterValue": "/fd sha256"
          },
          {
            "parameterName": "TimeStamp",
            "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
          }
        ],
        "toolName": "signtool.exe",
        "toolVersion": "6.2.9304.0"
      },
      {
          "keyCode": "CP-230012",
          "operationSetCode": "SigntoolVerify",
          "parameters": [ ],
          "toolName": "signtool.exe",
          "toolVersion": "6.2.9304.0"
       }
    ]
  SIGN_PARAMS_IOS: |
    [
      {
        "keyCode": "CP-233039-Apple",
        "operationSetCode": "iOSSdkSign"
      }
    ]
  SIGN_PARAMS_MACOS: |
    [
      {
        "keyCode": "CP-401337-Apple",
        "operationSetCode": "MacAppDeveloperSign"
      }
    ]
  SPEECHSDK_MAVEN_ARTIFACT_ID: client-sdk
  SPEECHSDK_MAVEN_GROUP_ID: com.microsoft.cognitiveservices.speech
  SPEECHSDK_NUGET_VERSION: 4.6
  AZURE_CONTAINER_REGISTRY_NAME: csspeechsdkacr201809
  AZURE_CONTAINER_REGISTRY: $(AZURE_CONTAINER_REGISTRY_NAME).azurecr.io
  AZURE_SUBSCRIPTION_ENDPOINT: 'Custom Speech Development (3a96ef56-41a9-40a0-b0f3-fb125c2b8798) - RG csspeechsdk-carbon'
  CG_RAN: true # we do Component Governance explicitly only in the Pre job

jobs:

- template: build-jobs.yml
  parameters:
    # Note: these template expressions match the expressions for build types in set-variables.sh
    ${{ if and(eq(variables['System.CollectionId'], '19422243-19b9-4d85-9ca6-bc961861d287'), eq(variables['System.DefinitionId'], '4833'), and(or(eq(variables['Build.Reason'], 'Schedule'), eq(variables['Build.Reason'], 'Manual')), eq(variables['Build.SourceBranch'], 'refs/heads/master'))) }}:
      buildType: int
      continueOnTestFailure: true
    ${{ if and(eq(variables['System.CollectionId'], '19422243-19b9-4d85-9ca6-bc961861d287'), eq(variables['System.DefinitionId'], '4833'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
      buildType: prod
      continueOnTestFailure: true
    ${{ if not(and(eq(variables['System.CollectionId'], '19422243-19b9-4d85-9ca6-bc961861d287'), eq(variables['System.DefinitionId'], '4833'), or(and(or(eq(variables['Build.Reason'], 'Schedule'), eq(variables['Build.Reason'], 'Manual')), eq(variables['Build.SourceBranch'], 'refs/heads/master')), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))) }}:
      buildType: dev
      continueOnTestFailure: false
