# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license.
#
# If you run into issue wrt. referenced resources when settings this build up, cf. here:
#   https://github.com/Microsoft/vsts-agent/issues/1301 wrt. ConnectedServiceName
#
# TODO describe parameters
resources:
- repo: self
  clean: true

variables:
- template: templates/subscription_vars.yml
- template: templates/sign_params_vars.yml
- name: SPEECHSDK_MAVEN_ARTIFACT_ID
  value: client-sdk
- name: SPEECHSDK_MAVEN_GROUP_ID
  value: com.microsoft.cognitiveservices.speech
- name: SPEECHSDK_NUGET_VERSION
  value: 4.6
- name: AZURE_CONTAINER_REGISTRY_NAME
  value: csspeechsdkacr201809
- name: AZURE_CONTAINER_REGISTRY
  value: $(AZURE_CONTAINER_REGISTRY_NAME).azurecr.io
- name: AZURE_SUBSCRIPTION_ENDPOINT
  value: 'Custom Speech Development (3a96ef56-41a9-40a0-b0f3-fb125c2b8798) - RG csspeechsdk-carbon'
- name: CG_RAN
  value: true # we do Component Governance explicitly only in the Pre job

jobs:

- template: build-jobs.yml
  parameters:
    #Note: these template expressions match the expressions for build types in set-variables.sh
    ${{ if and(eq(variables['System.CollectionId'], '19422243-19b9-4d85-9ca6-bc961861d287'), eq(variables['System.DefinitionId'], '4833'), and(or(eq(variables['Build.Reason'], 'Schedule'), eq(variables['Build.Reason'], 'Manual')), eq(variables['Build.SourceBranch'], 'refs/heads/master'))) }}:
      buildType: int
      continueOnTestFailure: true
    ${{ if and(eq(variables['System.CollectionId'], '19422243-19b9-4d85-9ca6-bc961861d287'), eq(variables['System.DefinitionId'], '4833'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
      buildType: prod
      continueOnTestFailure: true
    ${{ if not(and(eq(variables['System.CollectionId'], '19422243-19b9-4d85-9ca6-bc961861d287'), eq(variables['System.DefinitionId'], '4833'), or(and(or(eq(variables['Build.Reason'], 'Schedule'), eq(variables['Build.Reason'], 'Manual')), eq(variables['Build.SourceBranch'], 'refs/heads/master')), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))) }}:
      buildType: dev
      continueOnTestFailure: false
