jobs:
- job: OsxPythonBuild
  dependsOn: Pre
  condition: and(succeeded(), contains(dependencies.Pre.outputs['var.SPEECHSDK_BUILD_PHASES'], ' OsxPythonBuild '))
  pool:
    name: Hosted macOS Preview
  timeoutInMinutes: 60
  strategy:
    maxParallel: 1
    matrix:
      Python3.7:
        PythonVersion: 3.7
        pythonIncludePathSuffix: python3.7m
      Python3.6:
        PythonVersion: 3.6
        pythonIncludePathSuffix: python3.6m
      Python3.5:
        PythonVersion: 3.5
        pythonIncludePathSuffix: python3.5m
  variables:
    BuildConfiguration: Release
    BuildPlatform: x64
    WheelParams: "--plat-name macosx-10.12-x86_64"
    OutputDirectory: "$(Build.ArtifactStagingDirectory)/wheelhouse"
  steps:
  - task: ms-devlabs.utilitytasks.task-Shellpp.Shell++@0
    displayName: Set OSX-x64 target platform
    inputs:
      type: InlineScript
      script: |
        . ci/functions.sh
        vsts_setvar SPEECHSDK_TARGET_PLATFORM OSX-x64
        vsts_setvar SPEECHSDK_BUILD_CONFIGURATION "$(BuildConfiguration)"
        vsts_setvar SPEECHSDK_PYTHON_PLATFORM "$(BuildPlatform)"
        vsts_setvar SPEECHSDK_CMAKE_GENERATOR "Unix Makefiles"
  - bash: ./ci/set-variables.sh
    displayName: Set variables
  - bash: ./ci/install-build-dependencies.sh
    displayName: Install build dependencies
  - template: build-python-wheel.yml
    parameters:
      pythonIncludePathSuffix: $(PythonIncludePathSuffix)
      wheelParams: $(WheelParams)

